### ISSUE TITLE
Feature: Make this repo is "zero config"

### ISSUE THREAD

**Issue by kimyvgy** [kimyvgy/donate-page#1]
## Idea

1. Add configuration file for example:

```yaml
website:
  title: string
  description: string
  featureImage: string

analytics:
  google-analytics-id: string

donateMethods:
  momo:
    url: string
  paypal:
    url: string
  buymeacoffee:
    url: string

theme:
  primary:
  # ... something like that
```

2. Add Github Actions to build and deploy to Github Pages via `gh-pages` branch
